### ISSUE TITLE
请问一下coding.net的api文档在哪？

### ISSUE THREAD

**Issue by xiebruce** [zytomorrow/picgo-plugin-coding#1]
网上我能搜到的就是这个文档[CODING 开放平台](https://open.coding.net/open-api/)，这里并没有上传相关的api文档，所以有点好奇你是在哪里看到api文档的呢？

**Comment by zytomorrow** [comment]
官方给的是个实例，也就说网页上所有的接口都可以通过实例的传token形式使用。所以自己抓下接口就可以了，接口太多了，官方应该不会都给文档

**Comment by xiebruce** [comment]
哦哦，你说的实例，是用户和项目这两个吗？
![image](https://user-images.githubusercontent.com/13575500/80093944-f9756e00-8597-11ea-83e1-e3bd3acb2946.png)

**Comment by zytomorrow** [comment]
抱歉，是示例，就是那几个curl命令的使用。那个curl命令传达的就是请求头加token就可以使用api。至于那个上传api在哪里，网页上不是可以上传文件嘛，那个请求就是

**Comment by xiebruce** [comment]
哦哦，原来是这样，不过感觉api多并不是他们不写api的理由吧，因为不管是国外的github还是国内的gitee，都是有详细api文档的，coding.net不写文档估计是没想要让用户通过api上传吧。

**Comment by zytomorrow** [comment]
Token使用方式都告诉我了，然后不让我用api上传，那特么就是自欺欺人了啊，哈哈哈

**Comment by xiebruce** [comment]
哈哈，厉害！

**Comment by xiebruce** [comment]
我用postman试了一下，提示“提交内容不能为空”，不知道`uploadFile`部分是不是这么写？
![image](https://user-images.githubusercontent.com/13575500/80173311-fb840f00-8621-11ea-89a9-43fae1d8528e.png)
其中`uploadFile[value]`我是读取到文件内容并base64 encode了的，而且我也复制全了，应该不会说少复制一个字符导致这问题。

另外我试了一下在网页上传，上传的api确实是你用的那个，但它的`formData`里上传文件部分，并不是像你代码里的这种`uploadFile`这样，不知道你这个`uploadFile`这个结构是在哪个请求里发现的呢？
```json
uploadFile: {
      value: image,
      options: {
        filename: fileName
      }
}
```

如图，`Xnip2020-04-13_15-30-13.jpg`是我上传的图片文件名，`binary`就是直接上传二进制呗？
![image](https://user-images.githubusercontent.com/13575500/80174193-7e0dce00-8624-11ea-94d7-d184274b6ef1.png)

**Comment by zytomorrow** [comment]
![image](https://user-images.githubusercontent.com/16175551/80174776-4d2e9880-8626-11ea-8b41-4d88df85fb8c.png)
postman 需要这么传参


至于代码那块我是用的formdata传参的形式，request支持好几种formdata的形式，都尝试了一下，就这个形式可以

**Comment by zytomorrow** [comment]
![image](https://user-images.githubusercontent.com/16175551/80174969-de9e0a80-8626-11ea-9527-2d7dd659497d.png)
这几种依次尝试发现了可使用的。平时是些python的，不是很熟悉nodejs的库

**Comment by xiebruce** [comment]
> ![image](https://user-images.githubusercontent.com/16175551/80174776-4d2e9880-8626-11ea-8b41-4d88df85fb8c.png)
> postman 需要这么传参
> 
> 至于代码那块我是用的formdata传参的形式，request支持好几种formdata的形式，都尝试了一下，就这个形式可以

果然，你这种形式就是跟我在网页请求里看到的形式一样，但有点不明白的是，不管postman还是js又或者是其它语言，最终发起的都是一个http请求，理论上应该不存在js能而postman不能的情况吧？或者反过来，在代码里肯定也可以用postman里的形式才对，我目前在postman里用你说的形式测试成功，但在代码里一直报`{"code":1232,"msg":{"can_not_parse_upload_files":"无法解析上传文件"}}`，不管用你代码里的参数结构，还是用postman里的那个参数结构，都报同样错误，我用的php。

**Comment by zytomorrow** [comment]
python正常的，应该是js库的问题，包装formdata的形式不一样。没理解到，但是官方提供了那么多种formdata的形式，估计就是为了以防万一

**Comment by xiebruce** [comment]
哦哦，我再看看是哪儿有问题吧，一直都是无法解析上传文件 🤣

**Comment by xiebruce** [comment]
昨天已经解决了忘回了，之前理解错了，原来这个结构只是nodejs里的一种写法，我还以为是直接把这参数传给目标api的呢：
```
uploadFile: {
      value: image,
      options: {
        filename: fileName
      }
}
``
感谢解答！

**Comment by zytomorrow** [comment]
这是包裹formdata的一种方法形式，解决了就好

**Comment by xiebruce** [comment]
嗯，其实这种最终发送的数据是这样的：[Multipart/form-data](https://www.jianshu.com/p/e810d1799384)，就是那个`boundary`是关键

**Comment by zytomorrow** [comment]
是的，但是其他的写法都传不过去数据，是个很奇怪的事

**Comment by xiebruce** [comment]
目前看来是必须按网页里的那个接口，也就是传这几个参数：
![image](https://user-images.githubusercontent.com/13575500/80338865-fe843700-888f-11ea-9718-dafd43caf54f.png)
前三个参数都没啥，主要是第四个，文件参数，要额外用header指定它的类型，在postman不需要指定，是因为postman传的时候会自动指定，而用代码就必须自己指定了，不同语言可能指定的方式有区别，但应该都大同小异。

其实`newRef`这个参数也有个要注意，它是指定分支名，当指定的分支不存在时，会自动创建，但是，指定的分支不在，就表示该分支不存在`lastCommitSha`，可是`lastCommitSha`是必须的参数，要怎么拿？其实是要拿master的`lastCommitSha`，并且此时POST api的最后一级，也是指定到master => `upload/master`，而当新分支创建后(已存在)，则api就变成: `upload/new_master_name`，并且`lastCommitSha`也要用`new_master_name`这个分支对应的`lastCommitSha`了，另外，api最后一级，即分支的后面，还可以跟着文件夹路径，比如：`upload/master/newFolder/newSubfolder`，它会自动递归创建文件夹，这些是我试出来的。

**Comment by zytomorrow** [comment]
你可真能折腾，不过分支这个我目前用不上。那个库全是用来放图片的，我满足了基本功能就行，你这把这个接口摸清了，可以改一下多分支上传，这样不同类型的文章的图片传不同分支挺好的

**Comment by xiebruce** [comment]
我现在实现的是：
- 可填分支名，当填的分支不存在，会自动创建
- 可填文件夹(多级)，当文件夹不存在时，它会自动创建
- 填写的分支和文件夹都不存在时，它也能自动同时创建

**Comment by zytomorrow** [comment]
这个方法可以~管理更方便了~

**Comment by xiebruce** [comment]
嗯，我都习惯图片按`/年/月/日/`这样存放的。

**Comment by zytomorrow** [comment]
新版本已支持`/年/月/日`的存放方式
