### ISSUE TITLE
coding新的page服务转腾讯云对象存储了

### ISSUE THREAD

**Issue by Ryan-Miao** [zytomorrow/picgo-plugin-coding#11]
coding新的page转对象存储了，免费羊毛没了

**Comment by zytomorrow** [comment]
不走page的话还是可以走原来的url。我看我博客都还能用，应该不影响使用
![image](https://user-images.githubusercontent.com/16175551/98780898-80087480-2430-11eb-96c6-9cefd1fc2a37.png)

**Comment by Ryan-Miao** [comment]
看了官方文档，新版稳定后，旧版会关闭，以后会走腾讯云对象存储。放弃了。
