### ISSUE TITLE
如何修改自定义域名呢？并不像github图床一样可以改自定义域名啊。

### ISSUE THREAD

**Issue by wyz741525741** [zytomorrow/picgo-plugin-coding#2]
我是一个编程小白 不从事计算机行业，希望解答稍微详细一点

**Comment by zytomorrow** [comment]
coding的网址是以 自定义二级域名.coding.net 形式的。官方的自定义域名我没怎么去看过，好像是没有这功能，只有pages提供了自定义域名的功能，如果自已想弄的话，试试cname能不能映射过来~

**Comment by zytomorrow** [comment]
#8 🆕 支持自定义域名 新版本已加入自定义域名
