### ISSUE TITLE
重名的文件能处理吗？

### ISSUE THREAD

**Issue by ssmmtt** [zytomorrow/picgo-plugin-coding#29]
重名的文件上传时覆盖还是跳过？

**Comment by zytomorrow** [comment]
这部分没试过，尝试后我看下处理方案

**Comment by ssmmtt** [comment]
> 这部分没试过，尝试后我看下处理方案

我看见picgo有重命名的选项，上传之前会弹出。

**Comment by zytomorrow** [comment]
picgo应该只检测本地记录。我担心的是本地没有的话，git库里有，这种情况会是啥结果

**Comment by ssmmtt** [comment]
picgo可以使用时间戳

> picgo应该只检测本地记录。我担心的是本地没有的话，git库里有，这种情况会是啥结果

如果能检测到远端重复，后面追加序号，这样最好了。

**Comment by zytomorrow** [comment]
> 

可以，明天空了就考虑实现下
