### ISSUE TITLE
能否自动转义字符?

### ISSUE THREAD

**Issue by foxdodo** [zytomorrow/picgo-plugin-coding#33]
图片名字中带有`río`这种拉丁字母就会出现上传成功却无法显示的情况, 右下角提示了上传成功但是仓库中却没有图片. 把名字改成正常的英文再上传就能在仓库里正常显示

**Comment by zytomorrow** [comment]
picgo-core核心自带了上传重命名，可以开启该选项。
coding目前是无法使用拉丁字母的
<img width="707" alt="image" src="https://user-images.githubusercontent.com/16175551/171989403-a859db9e-48e5-46fc-bd49-4f3397fa24ad.png">

**Comment by foxdodo** [comment]
找到选项了,谢谢
