### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by luzy99** [zytomorrow/picgo-plugin-coding#7]
可以添加设置自定义域名的功能吗？我想通过coding的构建计划将图片同步到GitHub仓库，再获取jsdeliver的地址。（为了解决github上传失败率太高的问题）

**Comment by zytomorrow** [comment]
我没找到coding设置自定义域名的设置项，应该是不支持该选项。

**Comment by zytomorrow** [comment]
有个比较迂回的设置方式：构建coding pages然后再取pages的地址作为图床地址。哈哈哈，功能稍后加上

**Comment by luzy99** [comment]
我想的是，只要像GitHub图床那样加个配置项，手动输入域名就行
![image](https://user-images.githubusercontent.com/43703357/91116389-d3371a80-e6be-11ea-9e3d-41ccab092366.png)
至于取pages的地址还是别的可以自己定。
比如我想自定义域名`https://cdn.jsdelivr.net/gh/luzy99/cdn@latest/`，就把返回的链接
`https://luzy999.coding.net/p/cdn/d/cdn/git/raw/master/img/20200824234259.png`替换成`https://cdn.jsdelivr.net/gh/luzy99/cdn@latest/img/20200824234259.png`

本来我想自己改的，无奈node.js不太会，谢谢大佬了！

**Comment by zytomorrow** [comment]
稍后我确认下，应该是可行的

**Comment by zytomorrow** [comment]
有个问题需要确认下，你这个github的库配置了cname访问，然后在配置项里添加的域名吗

**Comment by luzy99** [comment]
> 有个问题需要确认下，你这个github的库配置了cname访问，然后在配置项里添加的域名吗

您是指`https://cdn.jsdelivr.net/gh/luzy99/cdn`这个域名吗？这个是白嫖的jsDelivr的cdn，不需要配置。我觉得这个插件不需要自动获取域名啥的，自己部署了page，再把域名贴过来就行

**Comment by zytomorrow** [comment]
ok,那明白了

**Comment by zytomorrow** [comment]
#8 🆕 支持自定义域名
